version: '3.1'

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '13306:3306'
    volumes:
      - mysql:/var/lib/mysql
  postgres:
    container_name: postgres
    image: postgres:12.10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: always
    command:
      - --requirepass "1234"
    ports:
      - '6370:6370'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  mariadb:
  mysql:
  redis:
