
spring:
    config:
        activate:
            on-profile: prod
server:
    port: 53103

---
spring:
    config:
        activate:
            on-profile: dev
server:
  port: 53102
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 53101
---
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

spring:
  profiles:
    active: local
    group:
      "local": "localdb,common"
      "dev": "edudb,common"
      "prod": "proddb,common"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

  servlet:
    multipart:
      max-request-size: 10240KB #?? ?? ??? : 10MB
      max-file-size: 10240KB #?? ?? ??? : 10MB

  redis:
    lettuce:
      pool:
        max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
        max-idle: 5 # pool의 'idle' 커넥션 최대수
        min-idle: 2
    host: localhost
    port: 6370

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    kr.weareboard.lp.api: debug
#    org:
#      hibernate:
#        sql: debug # debug로 하지 않으면 debug, info log 2개씩 나오게 됨
#        tool.hbm2ddl: debug
#        type.descriptor.sql: trace # Hibernate 4,5
#        orm.jdbc.bind: trace # Hibernate 6

jwt:
  secret: asdfbjahdslfjh2edoiughdivjhsxlkjvcahxclksdfhieduwhgowieurhgoeirufhsdlfddjvkahlsxckvjhasdlkjvchlkj34htop23i4uythoiuerwjhgasdvdgouasyv987d6v987
---
spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    url: jdbc:mariadb://localhost:58306/plz?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
    username: root
#        password: 1234
    password: leehj12!$
#    url: jdbc:mariadb://14.45.108.75:3306/laundry?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
#    username: laundry
#    password: jsolwpdlthffntus750!@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1f6ad7dc1f3d826e6746ea3b817c7f69
            redirect-uri: https://weareboard.kr/lp/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
---
spring:
  config:
    activate:
      on-profile: "localdb"

  datasource:
    url: jdbc:mariadb://localhost:58306/plz_edu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
    username: root
#    password: 1234
    password: leehj12!$
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1f6ad7dc1f3d826e6746ea3b817c7f69
            client-secret: V93uw4skZciXhDEcy5OHUVQFAZSwcKqI
            redirect-uri: http://localhost:53101/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id